# Generated by Django 6.0.2 on 2026-02-22 19:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("clients", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="JobcardTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("layout_schema", models.JSONField(help_text="Form.io JSON schema")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="LineItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("who_helped", models.CharField(max_length=255)),
                ("hardware_used", models.CharField(blank=True, max_length=255)),
                ("quantity", models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name="Jobcard",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "jobcard_id",
                    models.CharField(editable=False, max_length=20, unique=True),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("PENDING_REVIEW", "Pending Manager Review"),
                            ("PENDING_INVOICING", "Pending Invoicing"),
                            ("ARCHIVED", "Archived"),
                        ],
                        default="DRAFT",
                        max_length=20,
                    ),
                ),
                ("start_time", models.DateTimeField(blank=True, null=True)),
                ("end_time", models.DateTimeField(blank=True, null=True)),
                (
                    "technician_signature",
                    models.ImageField(
                        blank=True, null=True, upload_to="signatures/tech/"
                    ),
                ),
                (
                    "client_signature",
                    models.ImageField(
                        blank=True, null=True, upload_to="signatures/client/"
                    ),
                ),
                ("manager_notes", models.TextField(blank=True)),
                (
                    "manager_signature",
                    models.ImageField(
                        blank=True, null=True, upload_to="signatures/manager/"
                    ),
                ),
                (
                    "invoice_pdf",
                    models.FileField(blank=True, null=True, upload_to="invoices/"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="jobcards",
                        to="clients.clientprofile",
                    ),
                ),
            ],
        ),
    ]
